import express from 'express';
import Database from 'better-sqlite3';
import { mkdirSync } from 'node:fs';
import matter from 'gray-matter';
import { readFileSync, statSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const CONTENT_DIR = process.env.GIEO_CONTENT || join(process.cwd(), '..', 'content');
// Downloaded study materials (audio/pdf/img/video). PERSONAL/LOCAL ONLY — copyrighted courses;
// must be gated (per-user private) before any multi-user deploy.
const MATERIALS_DIR = process.env.GIEO_MATERIALS || '/home/azureuser/laged-app/materials-raw';
// Sidecar VTT transcripts for audio materials, generated by scripts/transcribe-materials.mjs.
// Layout mirrors MATERIALS_DIR: <TRANSCRIPTS_DIR>/<material src>.vtt → GET /transcripts/<src>.vtt
const TRANSCRIPTS_DIR = process.env.GIEO_TRANSCRIPTS || join(MATERIALS_DIR, '..', 'materials-transcripts');

const DB_PATH = process.env.GIEO_DB || '/data/gieo.db';
const PORT    = Number(process.env.PORT || 3000);

mkdirSync(DB_PATH.replace(/\/[^/]+$/, ''), { recursive: true });

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
db.exec(`
  CREATE TABLE IF NOT EXISTS state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  );
  CREATE TABLE IF NOT EXISTS writing (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    task TEXT,
    band_tr REAL, band_cc REAL, band_lr REAL, band_gra REAL, band_overall REAL,
    note TEXT,
    created_at INTEGER NOT NULL
  );
`);

// Content cache — invalidate by file mtime
const contentCache = new Map();
function readContent(absPath) {
  const stat = statSync(absPath);
  const cached = contentCache.get(absPath);
  if (cached && cached.mtimeMs === stat.mtimeMs) return cached.parsed;
  const text = readFileSync(absPath, 'utf8');
  const { data, content } = matter(text);
  const parsed = { ...data, body: content.trim() || null };
  contentCache.set(absPath, { mtimeMs: stat.mtimeMs, parsed });
  return parsed;
}

const getState = db.prepare('SELECT json FROM state WHERE id = 1');
const upsertState = db.prepare(`
  INSERT INTO state (id, json, updated_at) VALUES (1, ?, ?)
  ON CONFLICT(id) DO UPDATE SET json = excluded.json, updated_at = excluded.updated_at
`);
const listWriting   = db.prepare('SELECT * FROM writing ORDER BY date DESC, id DESC LIMIT 200');
const insertWriting = db.prepare(`
  INSERT INTO writing (date, task, band_tr, band_cc, band_lr, band_gra, band_overall, note, created_at)
  VALUES (@date, @task, @band_tr, @band_cc, @band_lr, @band_gra, @band_overall, @note, @created_at)
`);

const app = express();
app.use(express.json({ limit: '64kb' }));

// Permissive CORS for dev (frontend served separately from API in dev).
// Production deploys serve both same-origin so this is a no-op there.
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

// Static route for downloaded study materials (see MATERIALS_DIR note above).
if (existsSync(MATERIALS_DIR)) app.use('/materials', express.static(MATERIALS_DIR));
if (existsSync(TRANSCRIPTS_DIR)) app.use('/transcripts', express.static(TRANSCRIPTS_DIR));

app.get('/api/health', (_req, res) => res.json({ ok: true, t: Date.now() }));

app.get('/api/state', (_req, res) => {
  const row = getState.get();
  res.json(row ? JSON.parse(row.json) : null);
});

app.put('/api/state', (req, res) => {
  upsertState.run(JSON.stringify(req.body ?? {}), Date.now());
  res.json({ ok: true });
});

app.get('/api/writing', (_req, res) => res.json(listWriting.all()));

app.post('/api/writing', (req, res) => {
  const b = req.body ?? {};
  const row = {
    date: String(b.date || new Date().toISOString().slice(0, 10)),
    task: b.task ?? null,
    band_tr: b.band_tr ?? null, band_cc: b.band_cc ?? null,
    band_lr: b.band_lr ?? null, band_gra: b.band_gra ?? null,
    band_overall: b.band_overall ?? null,
    note: b.note ?? null,
    created_at: Date.now(),
  };
  const out = insertWriting.run(row);
  res.json({ ok: true, id: out.lastInsertRowid });
});

// ──────────────────────────────────────────────────────────────
// Content endpoints — read-only, served from CONTENT_DIR
// ──────────────────────────────────────────────────────────────

app.get('/api/courses', (_req, res) => {
  const coursesDir = join(CONTENT_DIR, 'courses');
  if (!existsSync(coursesDir)) return res.json([]);
  const list = readdirSync(coursesDir, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => {
      const file = join(coursesDir, e.name, 'course.md');
      if (!existsSync(file)) return null;
      try {
        const c = readContent(file);
        return {
          id: c.id, code: c.code, from: c.from, to: c.to,
          name: c.name, months: c.months, days: c.days,
          blocks_per_day: c.blocks_per_day, per_day: c.per_day,
          tree: c.tree, recommended: !!c.recommended,
        };
      } catch { return null; }
    })
    .filter(Boolean);
  res.json(list);
});

app.get('/api/courses/:id', (req, res) => {
  const file = join(CONTENT_DIR, 'courses', req.params.id, 'course.md');
  if (!existsSync(file)) return res.status(404).json({ error: 'course_not_found' });
  try {
    res.json(readContent(file));
  } catch (err) {
    res.status(500).json({ error: 'parse_error', detail: String(err.message) });
  }
});

app.get('/api/courses/:id/weeks/:n', (req, res) => {
  const n = String(req.params.n);
  const file = join(CONTENT_DIR, 'courses', req.params.id, 'weeks', `w${n}.md`);
  if (!existsSync(file)) return res.status(404).json({ error: 'week_not_found' });
  try {
    res.json(readContent(file));
  } catch (err) {
    res.status(500).json({ error: 'parse_error', detail: String(err.message) });
  }
});

// POC/local only: serve the static frontend same-origin (opt-in via GIEO_FRONTEND env).
// Same-origin avoids cross-port CORS and browser tracking-prevention storage blocks. Off by default.
if (process.env.GIEO_FRONTEND && existsSync(process.env.GIEO_FRONTEND)) {
  app.use(express.static(process.env.GIEO_FRONTEND));
}

app.listen(PORT, '0.0.0.0', () => console.log(`gieo-api on :${PORT} · db=${DB_PATH}`));
